### ISSUE TITLE
Hope this helps

### ISSUE THREAD

**Issue by ghost** [jboecker/dcs-witchcraft#2]
Windows 8.1 x64
DCS: World 1.5.4.57288 (Current as of 10/22/2016)

Connects fine, console appears to be working for the most part, but I don't know enough about this to tell you for sure, but the map editor definitely will not connect. I included a lua console response to show that was working but right after it is the attempt to connect the map with the server.

```
luaresult { name: '1477120805151',
  result:
   [ 'Unit #002',
     'Unit #003',
     'Unit #004',
     'Unit #005',
     'Unit #006',
     'Unit #007',
     'Unit #008',
     'Unit #009',
     'Unit #010',
     'Unit #011',
     'Unit #012',
     'Unit #1',
     'Unit #001' ],
  success: true,
  type: 'luaresult' }
luaresult { name: '1477120813758',
  result:
   { coalition: { blue: [Object], red: [Object] },
     coalitions: { blue: [Object], neutrals: [Object], red: [Object] },
     currentKey: 333,
     date: { Day: 1, Month: 6, Year: 2011 },
     descriptionBlueTask: 'DictKey_descriptionBlueTask_3',
     descriptionRedTask: 'DictKey_descriptionRedTask_2',
     descriptionText: 'DictKey_descriptionText_1',
     failures:
      { AAR_47_FAILURE_SENSOR_BOTTOM: [Object],
        AAR_47_FAILURE_SENSOR_LEFT: [Object],
        AAR_47_FAILURE_SENSOR_RIGHT: [Object],
        AAR_47_FAILURE_SENSOR_TAIL: [Object],
        AAR_47_FAILURE_TOTAL: [Object],
        AIRSPEED_INDICATOR_FAILURE: [Object],
        AN_ALE_40V_FAILURE_CONTAINER_LEFT_GEAR: [Object],
        AN_ALE_40V_FAILURE_CONTAINER_LEFT_WING: [Object],
        AN_ALE_40V_FAILURE_CONTAINER_RIGHT_GEAR: [Object],
        AN_ALE_40V_FAILURE_CONTAINER_RIGHT_WING: [Object],
        AN_ALE_40V_FAILURE_TOTAL: [Object],
        AN_ALR69V_FAILURE_SENSOR_NOSE_LEFT: [Object],
        AN_ALR69V_FAILURE_SENSOR_NOSE_RIGHT: [Object],
        AN_ALR69V_FAILURE_SENSOR_TAIL_LEFT: [Object],
        AN_ALR69V_FAILURE_SENSOR_TAIL_RIGHT: [Object],
        AN_ALR69V_FAILURE_TOTAL: [Object],
        CADC_FAILURE_BARO_ALT: [Object],
        CADC_FAILURE_DYNAMIC: [Object],
        CADC_FAILURE_IAS: [Object],
        CADC_FAILURE_MACH: [Object],
        CADC_FAILURE_PRESSURE_ALT: [Object],
        CADC_FAILURE_STATIC: [Object],
        CADC_FAILURE_TAS: [Object],
        CADC_FAILURE_TEMPERATURE: [Object],
        CADC_FAILURE_TOTAL: [Object],
        CDU_FAILURE_TOTAL: [Object],
        CICU_FAILURE_TOTAL: [Object],
        CLOCK_FAILURE: [Object],
        EGI_FAILURE_TOTAL: [Object],
        HUD_FAILURE: [Object],
        IFFCC_FAILURE_GUN: [Object],
        IFFCC_FAILURE_TOTAL: [Object],
        ILS_FAILURE_ANT_GLIDESLOPE: [Object],
        ILS_FAILURE_ANT_LOCALIZER: [Object],
        ILS_FAILURE_ANT_MARKER: [Object],
        ILS_FAILURE_TOTAL: [Object],
        LEFT_MFCD_FAILURE: [Object],
        RADAR_ALTIMETR_LEFT_ANT_FAILURE: [Object],
        RADAR_ALTIMETR_RIGHT_ANT_FAILURE: [Object],
        RIGHT_MFCD_FAILURE: [Object],
        SADL_FAILURE_TOTAL: [Object],
        TACAN_FAILURE_RECEIVER: [Object],
        TACAN_FAILURE_TOTAL: [Object],
        TACAN_FAILURE_TRANSMITTER: [Object],
        TGP_FAILURE_LEFT: [Object],
        TGP_FAILURE_RIGHT: [Object],
        UHF_RADIO_FAILURE_TOTAL: [Object],
        VHF_AM_RADIO_FAILURE_TOTAL: [Object],
        VHF_FM_RADIO_FAILURE_TOTAL: [Object],
        hydro_left: [Object],
        hydro_right: [Object],
        l_conv: [Object],
        l_engine: [Object],
        l_gen: [Object],
        r_conv: [Object],
        r_engine: [Object],
        r_gen: [Object],
        sas_pitch_left: [Object],
        sas_pitch_right: [Object],
        sas_yaw_left: [Object],
        sas_yaw_right: [Object] },
     forcedOptions: [],
     goals: [],
     groundControl: { isPilotControlVehicles: false, roles: [Object] },
     map: { centerX: -318718, centerY: 635685.42857142, zoom: 1000 },
     maxDictId: 59,
     needModules: [],
     pictureFileNameB: [],
     pictureFileNameR: [],
     result: { blue: [Object], offline: [Object], red: [Object], total: 0 },
     sortie: 'DictKey_sortie_4',
     start_time: 43200,
     theatre: 'Caucasus',
     trig:
      { actions: [Object],
        conditions: [Object],
        custom: [],
        customStartup: [],
        events: [],
        flag: [Object],
        func: [Object],
        funcStartup: [] },
     triggers: { zones: [] },
     trigrules: [ [Object] ],
     usedModules:
      { './CoreMods/aircraft/MQ-9 Reaper': true,
        'A-10A by Eagle Dynamics': false,
        'A-10C Warthog by Eagle Dynamics': true,
        AircraftWeaponPack: true,
        'Bf 109 K-4 by Eagle Dynamics': true,
        'C-101 Aviojet': true,
        'C-101 Aviojet by AvioDev': true,
        Caucasus: true,
        'Combined Arms by Eagle Dynamics': true,
        'F-15C': false,
        'F-5E by Belsimtek': true,
        'F-5E/E-3 by Belsimtek': true,
        'F-86F Sabre AI by Eagle Dynamics': true,
        'F-86F Sabre by Belsimtek': true,
        'FW-190D9 Dora by Eagle Dynamics': true,
        'Flaming Cliffs by Eagle Dynamics': true,
        'Hawk T.1A AI by VEAO Simulations': true,
        'Hawk T.1A by VEAO Simulations': true,
        'Ka-50 Black Shark by Eagle Dynamics': true,
        'L-39C': true,
        'L-39C/ZA by Eagle Dynamics': true,
        'M-2000C AI by RAZBAM Sims': true,
        'M-2000C by RAZBAM Sims': true,
        'Mi-8MTV2 Hip by Belsimtek': true,
        'MiG-15bis AI by Eagle Dynamics': true,
        'MiG-15bis by Belsimtek': true,
        'MiG-21Bis AI by Leatherneck Simulations': true,
        'MiG-21Bis by Leatherneck Simulations': true,
        'P-51D Mustang by Eagle Dynamics': true,
        'SA342 AI by Polychop-Simulations': true,
        'SA342 Gazelle by Polychop-Simulations': true,
        'Su-25A by Eagle Dynamics': false,
        'Su-25T by Eagle Dynamics': true,
        'Su-27 Flanker by Eagle Dynamics': false,
        'TF-51D Mustang by Eagle Dynamics': true,
        'UH-1H Huey by Belsimtek': true,
        'World War II AI Units by Eagle Dynamics': true },
     version: 12,
     weather:
      { atmosphere_type: 0,
        clouds: [Object],
        cyclones: [],
        enable_fog: false,
        fog: [Object],
        groundTurbulence: 0,
        name: 'Winter, clean sky',
        name_localize: [],
        qnh: 760,
        season: [Object],
        visibility: [Object],
        wind: [Object] } },
  success: true,
  type: 'luaresult' }
Missing error handler on `socket`.
TypeError: Cannot read property 'coalition' of undefined
    at C:\Users\skratch\Downloads\dcs-witchcraft-master\src\common\missionmodel.js:128:22
    at C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:4917:15
    at baseForOwn (C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:2979:24)
    at C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:4886:18
    at Function.forEach (C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:9289:14)
    at C:\Users\skratch\Downloads\dcs-witchcraft-master\src\common\missionmodel.js:127:6
    at C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:4917:15
    at baseForOwn (C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:2979:24)
    at C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:4886:18
    at Function.forEach (C:\Users\skratch\Downloads\dcs-witchcraft-master\src\node_modules\lodash\lodash.js:9289:14)

```

**Comment by jboecker** [comment]
The map editor has been broken ever since the mission file format changed. I haven't touched this project for about two years now.

Try [this mod](https://forums.eagle.ru/showthread.php?t=149769) instead.

I'll probably integrate the Lua console into some future version of DCS-BIOS and then officially scrap the project.

**Comment by ghost** [comment]
thank you
